### PR TITLE
Use Axios interceptor to retry request

### LINKED ISSUE #26: [CC Global Header] Retry API request on Failure
## Problem
API failures are not uncommon for a number of reasons including poor network, service availability etc. Initially mentioned in this [thread](https://github.com/creativecommons/cc-global-components/pull/20#discussion_r767667191) by @MuluhGodson 
>
>.......how about we use a method as you have said, and then have this method be called in the background if the API call is failing, say each time it fails, we wait for 5 seconds and try again...since it's reactive it would update seamlessly........
>

and also here on this [comment](https://github.com/creativecommons/cc-global-components/issues/16#issuecomment-995259171) by @TimidRobot 
>
>Also, ideally, after a few attempts at loading the menu, I think the text should change from "Loading Menu..." to "Menu Unavailable".
>

A request retry method will ensure that if the API call failed due to some temporal minor issue such as network connectivity, the menus will be rendered on the next retry instead of displaying a too-early error message.

## Task
The component that renders the Nav menu should retry calling the API if there's an error. With this in mind, we can improve the component by:
- [ ] add a retry feature (keeping in mind that we don't want to send too many requests or DDOS ourselves).
- [ ] if all the retries fail, display an informative message to the end-user/developer. Also [Task 3 here](https://github.com/creativecommons/cc-global-components/issues/25)

## Alternatives
Each time the user does an action that causes the component to re-render, such as a page reload or moving from one page to another, the API call will naturally be sent as the component is rendered.

## Additional context
- [How To Improve Your Backend By Adding Retries to Your API Calls](https://hackernoon.com/how-to-improve-your-backend-by-adding-retries-to-your-api-calls-83r3udx)
- [Retry Failed API Requests with JavaScript](https://markus.oberlehner.net/blog/retry-failed-api-requests-with-javascript/)
- [Axios Async/Await with Retry](https://dev.to/yogski/axios-async-await-with-retry-4j5j)

### PR DESCRIPTION
**Pull request by MuluhGodson**
## Fixes

Fixes #26  by @MuluhGodson 

## Description

Using [Axios interceptors](https://axios-http.com/docs/interceptors) which on the official documentation says this about it: 

>
>You can intercept requests or responses before they are handled by then or catch.
>

With this, we are able to get the errors and trigger a retry for the duration of time.  We have two variables passed to the Axios instance: 
- `retry`: Number of times to retry the request after first failed request.
- `retryDelay`: Number of milliseconds to wait in between failed requests (defaults to 1000).

The implementation of this was observed here [Axios retry with Exponential Backoff](https://lifesaver.codes/answer/adding-retry-parameter)

## Screenshots
I triggered an error by removing one character from the request URL. The retries continue to fail as observed on the console tab, but when I correct the missing character from the request URL it becomes successful.

https://user-images.githubusercontent.com/40151808/146537362-98516316-3b55-4ec8-8457-733f436e978b.mp4

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
      visible errors.

[best_practices]: https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/components/cc-global-header.vue [hunk 1]
```diff
@@ -128,11 +128,42 @@ export default defineComponent({
...
+          if (config.retryCount >= config.retry) {
+            // Reject with the errors
+            return Promise.reject(error);
+          }
+
+          // Increase the retry count
+          config.retryCount += 1;
+
+          // Create new promise for exponential backoff
+          var exponentialBackOff = new Promise(function (resolve) {
```
Comment (brylie) [inline src/components/cc-global-header.vue]: If I understand correctly, we're using a fixed retry delay. If that is the case, we don't need to call this "exponential backoff" since it might lead to confusion.
```suggestion
          var requestResolver = new Promise(function (resolve) {
```

File: src/components/cc-global-header.vue [hunk 2]
```diff
@@ -128,11 +128,42 @@ export default defineComponent({
...
+            setTimeout(function () {
+              resolve();
+            }, config.retryDelay || 1000);
```
Comment (brylie) [inline src/components/cc-global-header.vue]: Let's define an explanatory variable to use here.
```suggestion
            }, config.retryDelay || defaultRetryDelay);
```

File: src/components/cc-global-header.vue [hunk 3]
```diff
@@ -128,11 +128,42 @@ export default defineComponent({
       ];
     } else {
       vm.menuLoading = true;
+      axios.interceptors.response.use(
+        undefined,
+        function retryApiRequest(error) {
```
Comment (brylie) [inline src/components/cc-global-header.vue]: Let's move the function definition to the top of the JS Scope. E.g. right after the following block:

```js
if (process.env.NODE_ENV === "development") {
  var axios = require("axios");
} else {
  var axios = window.axios;
}

function retryApiRequest(error) {
  ...
}
```

File: src/components/cc-global-header.vue [hunk 4]
```diff
@@ -128,11 +128,42 @@ export default defineComponent({
...
+          var config = error.config;
+          // If config does not exist or the retry option is not set, reject
+          if (!config || !config.retry) return Promise.reject(error);
+
```
Comment (brylie) [inline src/components/cc-global-header.vue]: Somewhere around here, let's define an explanatory variable for the `defaultRetryDelay`

```suggestion
// Set the default retry delay in milliseconds
const defaultRetryDelay = 1000;
```

**Review by brylie — CHANGES_REQUESTED** [review]
A few changes for readability. I.e., our function doesn't need to be defined directly where it is used, so we can "hoist" it to the top-level scope.

One additional note, we should be able to use `let` and `const` here, since the code is being transpiled by Babel. Wherever we see `var`, switch it to the appropriate `let` or `const` depending on whether the reference will change.

File: src/components/cc-global-header.vue [hunk 5]
```diff
@@ -96,11 +96,43 @@ if (process.env.NODE_ENV === "development") {
...
+  return requestResolver.then(function () {
+    return axios(config);
+  });
+}
 export default defineComponent({
   name: "cc-golbal-header",
   created() {
     var vm = this;
-    var requestPath = "/?rest_route=/ccnavigation-header/menu";
+    var requestPath = "/?rest_route=/ccnavigation-header/men";
```
Comment (brylie) [inline src/components/cc-global-header.vue]: Is this a typo?
```suggestion
    var requestPath = "/?rest_route=/ccnavigation-header/menu";
```

Comment (MuluhGodson) [reply src/components/cc-global-header.vue]: It's how I was testing the failed API calls by triggering a 404 Not Found. I already corrected it in the latest commit.

**Review by brylie — APPROVED** [review]
